version: '2'
services:
  gmdy:
    image: morningborn/nginx1.18-php74-fpm-centos7.8:v2
    container_name: gmdy
    ports:
      - "0.0.0.0:9003:80"
    volumes:
      - /Users/apple/Downloads/gaoling/gmdy:/var/www/html
      - /Users/apple/Log/fxadmin/php_fpm_log:/var/log/php-fpm
      - /Users/apple/Downloads/gaoling/gmdy/server_name.conf:/etc/nginx/conf.d/server_name.conf
    cap_add:
      - SYS_PTRACE
